### ISSUE TITLE
Object not properly deserialized due to case-sensitivity

### ISSUE THREAD

**Issue by MiKom** [BlazorExtensions/SignalR#39]
Hi!

First of all, thanks for the library! It's great to have possibility to use SignalR in Blazor with C#.

I have an issue with deserialization of an object. There's an example code attached.

On client side I changed the Index component to subscribe to a hub and added a button to poke a controller on server side that sends an object through the hub.

Problem is, that all strings are empty in the object received in the client in method registered through `.On<>` (`OnPostReceived`). The contents of the received message is logged to console:

![image](https://user-images.githubusercontent.com/104767/60845994-5016e480-a1de-11e9-8c60-1205c90f476d.png)

When I looked at the packets through Wireshark they seemed to contain sensible data.

It's also possible that I'm doing something very wrong.

I'm using strongly-typed hub on the server, but I don't think it should matter.

[BlazorSignalR.zip](https://github.com/BlazorExtensions/SignalR/files/3370260/BlazorSignalR.zip)

**Comment by dave-bt** [comment]
I have the exact same issue. If I retrieve the object into my Blazor page using HttpClient it is populated, if I send the same object to my SignalR handler then the object's fields are all null. I may also be doing something very wrong - this is all rather new to me.

**Comment by MiKom** [comment]
Ok, I found out that the problem is related to case-sensitivity of names of properties in my object.

The object that I was trying to send down SignalR looks like that:
```csharp
    public class Post
    {
        public string Author { get; set; }
        public string Text { get; set; }
    }
```

Unfortunately, somewhere down the road in the `System.Text.Json` serializer on the server makes all property names lower-case before sending the object representation down the pipe. Client however, is more picky and expect exactly the same casing and thus, cannot match property names.

After changing my object to:
```csharp
    public class Post
    {
        public string author { get; set; }
        public string text { get; set; }
    }
```

It started working.

**Comment by MiKom** [comment]
I can see that I had `.AddNewtonsoftJson()` in my sample project after all, but it doesn't change anything because `System.Text.Json` and Newtonsoft Json both make serialized property names case-insensitive.

I can see that .Net client for SignalR core changed to also accept case-insensitive properties by default so it should be implemented as such in this client as well.

https://github.com/aspnet/AspNetCore/issues/10774

**Comment by MiKom** [comment]
This probably has to happen in `HubConnection.cs` where `JsonSerializer.Parse<>()` is called bunch of times. 

That's where case-(in)sensivity matters.

Maybe it should be configurable when setting up the hub connection like with `AddJsonProtocol` of regular SignalR client. Or maybe this Blazor client has limited scope and we shouldn't be so flexible and enable only the default.

**Comment by galvesribeiro** [comment]
Hello @MiKom 

Please open the PR if you are in the mood for that. It will be very much appreciated.

However, keep in mind that this package tries to only wrap the JS client as much as possible, 

So if there is something that the C# is interfering we should indeed tackle.

Thanks!

**Comment by MiKom** [comment]
I'll get to it tomorrow, it's getting late here :)

**Comment by MiKom** [comment]
@dave-bt To work around the problem before the fix is released you can force the Json serializer to always use lowercase property name like that:
```csharp
    public class Post
    {
        [JsonPropertyName("author")]
        public string Author { get; set; } = "";

        [JsonPropertyName("content")]
        public string Content { get; set; } = "";
    }
```

**Comment by dave-bt** [comment]
@MiKom Thank you very much indeed for that. Works a treat!

**Comment by galvesribeiro** [comment]
The preview7 package was published and it supports the `JsonPropertyName`. Please try it out.

**Comment by dradovic** [comment]
The property names parsing is still not case-insensitive, also in preview7 right? Are there any plans to make it so?

**Comment by galvesribeiro** [comment]
Yes, the current `System.Text.Json` requires you to use `JsonPropertyName`.
